# Generated by Django 4.0 on 2021-12-16 16:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=30)),
                ('date_naissance', models.DateField(default=django.utils.timezone.now)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='./Media/')),
                ('adress_email', models.EmailField(max_length=70, unique=True)),
                ('Added', models.DateField(default=django.utils.timezone.now)),
                ('id_etudiant', models.AutoField(primary_key=True, serialize=False)),
                ('etat_etudiant', models.CharField(choices=[('Abscent', 'Absence'), ('Exclu', 'Exclu'), ('Retard', 'Retard'), ('Present', 'Present')], max_length=10)),
                ('situation_etudiant', models.CharField(choices=[('Nouveau', 'Nouveau'), ('Redoublant', 'Redoublant'), ('Derogatrice', 'Derogatrice'), ('Autre', 'Autre')], max_length=20)),
            ],
            options={
                'db_table': 'etudiant',
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id_module', models.AutoField(primary_key=True, serialize=False)),
                ('nom_module', models.CharField(max_length=30, unique=True)),
                ('nbr_heures_module', models.PositiveIntegerField(default=0)),
                ('type_module', models.CharField(choices=[('Obligatoire', 'Obligatoire'), ('Optionnel', 'Optionnel')], default='Obligatoire', max_length=20)),
                ('niveau_etude', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'module',
            },
        ),
        migrations.CreateModel(
            name='Travail_A_Rendre',
            fields=[
                ('id_taf', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=50)),
                ('date_lancement', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_lim_retour', models.DateTimeField(default=django.utils.timezone.now)),
                ('nature', models.CharField(max_length=50)),
                ('descriptif_taf', models.CharField(max_length=200)),
                ('pieces_enonce', models.FileField(max_length=254, upload_to='./Media/')),
                ('pieces_rendu', models.FileField(max_length=254, upload_to='./Media/')),
                ('etat_travail', models.CharField(choices=[('Valide', 'Valid'), ('non valide', 'Non Valid')], default='Valide', max_length=10)),
                ('note', models.PositiveIntegerField(blank=True, default=0)),
                ('commentaire', models.CharField(max_length=100)),
                ('id_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_mangement.module')),
                ('travail_etud', models.ManyToManyField(to='student_mangement.Etudiant')),
            ],
            options={
                'db_table': 'travail_a_rendre',
            },
        ),
        migrations.CreateModel(
            name='Seance',
            fields=[
                ('id_seance', models.AutoField(primary_key=True, serialize=False)),
                ('heure_debut', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('heure_fin', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('num_salle', models.CharField(max_length=4)),
                ('objectif', models.CharField(blank=True, max_length=100)),
                ('resume', models.CharField(blank=True, max_length=500)),
                ('etat_seance', models.CharField(choices=[('Annulée', 'Annule'), ('Différée', 'Differe'), ('En cours', 'En Cours'), ('Términée', 'Termine')], max_length=10)),
                ('type_seance', models.CharField(choices=[('Normal', 'Normal'), ('Rattrapage', 'Rattrapage'), ('Soutien', 'Soutien'), ('Formation', 'Formation')], max_length=10)),
                ('outils', models.CharField(blank=True, max_length=100)),
                ('idModule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_mangement.module')),
            ],
            options={
                'db_table': 'seance',
            },
        ),
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('id_groupe', models.AutoField(primary_key=True, serialize=False)),
                ('nom_groupe', models.CharField(max_length=10)),
                ('nombre_etudiant', models.PositiveIntegerField(default=0)),
                ('mail_groupe', models.EmailField(blank=True, max_length=70, null=True)),
                ('niveau_etude', models.CharField(max_length=10)),
                ('module_groupe', models.ManyToManyField(blank=True, to='student_mangement.Module')),
            ],
            options={
                'db_table': 'Groupe',
            },
        ),
        migrations.AddField(
            model_name='etudiant',
            name='id_groupe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_mangement.groupe'),
        ),
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=30)),
                ('date_naissance', models.DateField(default=django.utils.timezone.now)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='./Media/')),
                ('adress_email', models.EmailField(max_length=70, unique=True)),
                ('Added', models.DateField(default=django.utils.timezone.now)),
                ('id_enseignant', models.AutoField(primary_key=True, serialize=False)),
                ('nbr_heure', models.PositiveIntegerField(default=0)),
                ('Modul_ensei', models.ManyToManyField(to='student_mangement.Module')),
            ],
            options={
                'db_table': 'enseignant',
            },
        ),
        migrations.CreateModel(
            name='Enregistrement',
            fields=[
                ('id_enreg', models.AutoField(primary_key=True, serialize=False)),
                ('nom_enreg', models.CharField(max_length=100, unique=True)),
                ('url', models.URLField(blank=True, max_length=100)),
                ('contenu_enreg', models.URLField(blank=True, max_length=100)),
                ('type_enreg', models.CharField(choices=[('mp4', 'Mp4'), ('flv', 'Flv'), ('mov', 'Mov'), ('avi', 'Avi'), ('wmv', 'Wmv')], max_length=4)),
                ('desrcription_enreg', models.CharField(blank=True, max_length=100)),
                ('date_enreg', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_seance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_mangement.seance')),
            ],
            options={
                'db_table': 'enregistrement',
            },
        ),
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id_absence', models.AutoField(primary_key=True, serialize=False)),
                ('date_absence', models.DateTimeField(default=django.utils.timezone.now)),
                ('motif', models.CharField(blank=True, max_length=100)),
                ('justificatif', models.CharField(blank=True, max_length=100)),
                ('Abs_se', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student_mangement.seance')),
                ('id_etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_mangement.etudiant')),
            ],
            options={
                'db_table': 'absence',
            },
        ),
    ]
