# Generated by Django 4.0 on 2021-12-17 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_mangement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=30)),
                ('adress_email', models.EmailField(max_length=70, unique=True)),
                ('say', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='groupe',
            name='niveau_etude',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='groupe',
            name='nom_groupe',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='travail_a_rendre',
            name='pieces_enonce',
            field=models.FileField(max_length=254, upload_to=''),
        ),
        migrations.AlterField(
            model_name='travail_a_rendre',
            name='pieces_rendu',
            field=models.FileField(max_length=254, upload_to=''),
        ),
    ]
